//! Regenerates `src/remote/lithos_models.zig` from the live roster.
//!
//! LithosAI's `GET /v1/models` is credential-scoped — it lists the models the
//! organization behind the key can call — so the roster is data, not code, and
//! this program fetches it and writes it out. It is a scratch program: not
//! installed, not built by the default step, which must stay off the network.
//!
//!   zig build --build-file ./build.research.zig lithos_models
//!
//! The key comes from the same place every other call gets it:
//! `LITHOSAI_API_KEY`, or omp's credential store.

const std = @import("std");
const Io = std.Io;
const harness1 = @import("harness1");
const lithos = harness1.lithos;
const keys = harness1.keys;
const debug = harness1.debug;

/// Relative to the build root.
const output_path = "src/remote/lithos_models.zig";

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;

    var stdout_buffer: [4096]u8 = undefined;
    var stdout_file = Io.File.stdout().writerStreaming(io, &stdout_buffer);
    const out = &stdout_file.interface;
    var stderr_buffer: [4096]u8 = undefined;
    var stderr_file = Io.File.stderr().writerStreaming(io, &stderr_buffer);
    const err_out = &stderr_file.interface;

    // The arena outlives the client that borrows the key.
    const arena = init.arena.allocator();
    const api_key = try keys.apiKey(arena, io, debug.writer(err_out), init.environ_map, keys.Provider.lithosai) orelse {
        try err_out.writeAll("no LithosAI key: set LITHOSAI_API_KEY, or sign in to the `lithosai` provider of omp\n");
        try err_out.flush();
        return error.ApiKeyRequired;
    };

    var client = try lithos.Client.init(gpa, io, api_key, .{});
    defer client.deinit();

    const result = try lithos.models.list(&client);
    const listed = switch (result) {
        .ok => |parsed| parsed,
        .err => |failure| {
            try err_out.writeAll("models request failed: ");
            try failure.format(err_out);
            try err_out.writeByte('\n');
            try err_out.flush();
            return error.RequestFailed;
        },
    };
    defer listed.deinit();

    const text = try render(gpa, listed.value.data);
    defer gpa.free(text);
    try Io.Dir.cwd().writeFile(io, .{ .sub_path = output_path, .data = text, .flags = .{} });

    try out.print("wrote {s}: {d} models\n", .{ output_path, listed.value.data.len });
    try out.flush();
}

/// The shape is fixed, so regenerating an unchanged roster produces identical
/// bytes.
fn render(allocator: std.mem.Allocator, roster: []const lithos.models.Model) ![]u8 {
    var allocating = std.Io.Writer.Allocating.init(allocator);
    defer allocating.deinit();
    const w = &allocating.writer;

    try w.writeAll(header);

    for (roster) |model| {
        try w.writeAll("    .{ .id = ");
        try writeLiteral(w, model.id);
        try w.print(", .created = {d}, .owned_by = ", .{model.created});
        try writeLiteral(w, model.owned_by);
        try w.writeAll(" },\n");
    }

    try w.writeAll(middle);

    for (roster) |model| {
        const name = try constantName(allocator, model.id);
        defer allocator.free(name);
        try w.print("    pub const {s} = ", .{name});
        try writeLiteral(w, model.id);
        try w.writeAll(";\n");
    }

    try w.writeAll(middle2);

    try w.writeAll("    const names = [_][]const u8{\n");
    for (roster) |model| {
        const name = try constantName(allocator, model.id);
        defer allocator.free(name);
        try w.print("        Model.{s},\n", .{name});
    }
    try w.writeAll(tail);

    return allocating.toOwnedSlice();
}

const header =
    \\//! LithosAI model roster, generated by `zig build --build-file ./build.research.zig lithos_models`.
    \\//!
    \\//! Fetched from `GET https://api.lithosai.cloud/v1/models`. The roster is
    \\//! account-scoped — the endpoint lists the models *this organization* can
    \\//! call, and answers 401 without a key — so re-running the step re-reads
    \\//! it rather than merging into it.
    \\//!
    \\//! The rows carry no limits, tariffs or capability metadata, so none is
    \\//! invented here. The constraints of individual models are in
    \\//! `lithos_models.md` beside this file; they are not in this type or in the
    \\//! client.
    \\//!
    \\//! Do not edit by hand.
    \\
    \\const std = @import("std");
    \\
    \\/// One row of the roster, exactly as the endpoint lists it.
    \\pub const Entry = struct {
    \\    /// The model id, as referenced in a request's `model` field.
    \\    id: []const u8,
    \\    /// Unix seconds the endpoint reports for the model's creation.
    \\    created: i64,
    \\    /// The organization the endpoint attributes the model to.
    \\    owned_by: []const u8,
    \\};
    \\
    \\/// The models `GET /v1/models` listed when this file was generated.
    \\pub const roster: []const Entry = &.{
    \\
;

const middle =
    \\};
    \\
    \\/// The roster row with this id, or null when the roster has none.
    \\pub fn find(id: []const u8) ?Entry {
    \\    for (roster) |entry| {
    \\        if (std.mem.eql(u8, entry.id, id)) return entry;
    \\    }
    \\    return null;
    \\}
    \\
    \\/// Named constants for the roster ids, so a caller names a model rather
    \\/// than spelling its deployment suffix. The names are the ids with every
    \\/// run of characters outside `[a-z0-9]` folded to one `_`.
    \\pub const Model = struct {
    \\
;

const middle2 =
    \\};
    \\
    \\test "the named constants are the roster ids" {
    \\
;

const tail =
    \\    };
    \\    try std.testing.expectEqual(roster.len, names.len);
    \\    for (names) |name| try std.testing.expect(find(name) != null);
    \\}
    \\
;

/// Writes `text` as a JSON/Zig string literal: wrapped in quotes, with the
/// two bytes that would end it escaped. Ids and owners contain neither, but a
/// generated file must still be valid Zig for any roster.
fn writeLiteral(writer: *std.Io.Writer, text: []const u8) std.Io.Writer.Error!void {
    try writer.writeByte('"');
    for (text) |byte| switch (byte) {
        '"' => try writer.writeAll("\\\""),
        '\\' => try writer.writeAll("\\\\"),
        else => try writer.writeByte(byte),
    };
    try writer.writeByte('"');
}

fn constantName(allocator: std.mem.Allocator, id: []const u8) ![]u8 {
    var buffer: std.ArrayList(u8) = .empty;
    errdefer buffer.deinit(allocator);
    var last_was_separator = false;
    for (id) |byte| {
        if (std.ascii.isAlphanumeric(byte)) {
            try buffer.append(allocator, std.ascii.toLower(byte));
            last_was_separator = false;
        } else if (!last_was_separator and buffer.items.len != 0) {
            try buffer.append(allocator, '_');
            last_was_separator = true;
        }
    }
    while (buffer.items.len != 0 and buffer.items[buffer.items.len - 1] == '_') {
        _ = buffer.pop();
    }
    return buffer.toOwnedSlice(allocator);
}