//! LithosAI model roster, generated by `zig build lithos_models`.
//!
//! Fetched from `GET https://api.lithosai.cloud/v1/models`. The roster is
//! account-scoped — the endpoint lists the models *this organization* can
//! call, and answers 401 without a key — so re-running the step re-reads
//! it rather than merging into it.
//!
//! The rows carry no limits, tariffs or capability metadata, so none is
//! invented here. The constraints of individual models are in
//! `lithos_models.md` beside this file; they are not in this type or in the
//! client.
//!
//! Do not edit by hand.

const std = @import("std");

/// One row of the roster, exactly as the endpoint lists it.
pub const Entry = struct {
    /// The model id, as referenced in a request's `model` field.
    id: []const u8,
    /// Unix seconds the endpoint reports for the model's creation.
    created: i64,
    /// The organization the endpoint attributes the model to.
    owned_by: []const u8,
};

/// The models `GET /v1/models` listed when this file was generated.
pub const roster: []const Entry = &.{
    .{ .id = "deepseek-ai/DeepSeek-V4.1-Flash", .created = 1788998400, .owned_by = "DeepSeek" },
    .{ .id = "deepseek-ai/DeepSeek-V4.1-Flash-fast", .created = 1788998400, .owned_by = "DeepSeek" },
    .{ .id = "deepseek-ai/DeepSeek-V4.1-Flash-ultra", .created = 1788998400, .owned_by = "DeepSeek" },
    .{ .id = "deepseek-ai/DeepSeek-V4.1-Flash-ultra-chat", .created = 1788998400, .owned_by = "DeepSeek" },
    .{ .id = "zai-org/GLM-5.3", .created = 1787616000, .owned_by = "Z.ai" },
    .{ .id = "zai-org/GLM-5.3-Flash", .created = 1787616000, .owned_by = "Z.ai" },
    .{ .id = "zai-org/GLM-5.3-Flash-ultra", .created = 1787616000, .owned_by = "Z.ai" },
    .{ .id = "zai-org/GLM-5.3-Flash-ultra-chat", .created = 1787616000, .owned_by = "Z.ai" },
    .{ .id = "zai-org/GLM-5.3-ultra-chat", .created = 1787616000, .owned_by = "Z.ai" },
    .{ .id = "moonshotai/Kimi-K3", .created = 1785110400, .owned_by = "Moonshot AI" },
    .{ .id = "moonshotai/Kimi-K3-fast", .created = 1785110400, .owned_by = "Moonshot AI" },
    .{ .id = "moonshotai/Kimi-K3-ultra", .created = 1785110400, .owned_by = "Moonshot AI" },
    .{ .id = "moonshotai/Kimi-K3-ultra-chat", .created = 1785110400, .owned_by = "Moonshot AI" },
};

pub fn find(id: []const u8) ?Entry {
    for (roster) |entry| {
        if (std.mem.eql(u8, entry.id, id)) return entry;
    }
    return null;
}

/// Named constants for the roster ids, so a caller names a model rather
/// than spelling its deployment suffix. The names are the ids with every
/// run of characters outside `[a-z0-9]` folded to one `_`.
pub const Model = struct {
    pub const deepseek_ai_deepseek_v4_1_flash = "deepseek-ai/DeepSeek-V4.1-Flash";
    pub const deepseek_ai_deepseek_v4_1_flash_fast = "deepseek-ai/DeepSeek-V4.1-Flash-fast";
    pub const deepseek_ai_deepseek_v4_1_flash_ultra = "deepseek-ai/DeepSeek-V4.1-Flash-ultra";
    pub const deepseek_ai_deepseek_v4_1_flash_ultra_chat = "deepseek-ai/DeepSeek-V4.1-Flash-ultra-chat";
    pub const zai_org_glm_5_3 = "zai-org/GLM-5.3";
    pub const zai_org_glm_5_3_flash = "zai-org/GLM-5.3-Flash";
    pub const zai_org_glm_5_3_flash_ultra = "zai-org/GLM-5.3-Flash-ultra";
    pub const zai_org_glm_5_3_flash_ultra_chat = "zai-org/GLM-5.3-Flash-ultra-chat";
    pub const zai_org_glm_5_3_ultra_chat = "zai-org/GLM-5.3-ultra-chat";
    pub const moonshotai_kimi_k3 = "moonshotai/Kimi-K3";
    pub const moonshotai_kimi_k3_fast = "moonshotai/Kimi-K3-fast";
    pub const moonshotai_kimi_k3_ultra = "moonshotai/Kimi-K3-ultra";
    pub const moonshotai_kimi_k3_ultra_chat = "moonshotai/Kimi-K3-ultra-chat";
};

test "the named constants are the roster ids" {
    const names = [_][]const u8{
        Model.deepseek_ai_deepseek_v4_1_flash,
        Model.deepseek_ai_deepseek_v4_1_flash_fast,
        Model.deepseek_ai_deepseek_v4_1_flash_ultra,
        Model.deepseek_ai_deepseek_v4_1_flash_ultra_chat,
        Model.zai_org_glm_5_3,
        Model.zai_org_glm_5_3_flash,
        Model.zai_org_glm_5_3_flash_ultra,
        Model.zai_org_glm_5_3_flash_ultra_chat,
        Model.zai_org_glm_5_3_ultra_chat,
        Model.moonshotai_kimi_k3,
        Model.moonshotai_kimi_k3_fast,
        Model.moonshotai_kimi_k3_ultra,
        Model.moonshotai_kimi_k3_ultra_chat,
    };
    try std.testing.expectEqual(roster.len, names.len);
    for (names) |name| try std.testing.expect(find(name) != null);
}
